[package]
name = "mccfr_poker"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = { version = "0.15.2", features = ["serde"] }
poker = "0.6.5"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde-pickle = "1.2.0"
serde_json = "1.0"
